- hosts: web
  tasks:
  - name: Install the latest version of Apache
    apt:
      name: apache2
      state: latest
  - name: Make sure a service is running
    systemd:
      name: apache2
      state: started
      enabled: yes
  - name: Install unzip
    apt:
      name: unzip
      state: latest
  - name: Unarchive a file that needs to be downloaded
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page283/ninom.zip
      dest: /var/www/
      remote_src: yes
  - name: Recursively change ownership of a directory
    file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: apache2
      group: apache2
